package(default_visibility = ["//visibility:public"])

java_binary(
    name = "MavenDependencyConverter",
    srcs = ["MavenDependencyConverter.java"],
    main_class = "src.MavenDependencyConverter",
)